### ISSUE TITLE
Cannot release new images due to PHP7 phpdbg segfaults

### ISSUE THREAD

**Issue by tyranron** [kahlan/docker-image#2]
Temporary cannot release new version of Kahlan images, as latest PHP7 phpdbg segfaults on Linux platforms.

**Comment by tyranron** [comment]
Tested it out with different scripts. Actually `phpdbg` works well, it only fails on `kahlan` binary.

Further investigation showed that the problem is in first line:
```bash
#!/usr/bin/env php
```

Removing this line stops `phpdbg` to segfault.

**Comment by tyranron** [comment]
Need to think about better workaround for `phpdbg`.

Also, @jails , maybe this can be "fixed" somehow in upstream? It's not relevant only to Docker images and will fail directly on Linux too.  
I'm talking about this command:
```bash
phpdbg -qrr kahlan --help
```

I undestand that it's rather `phpdbg` issue than `kahlan`.

**Comment by jails** [comment]
Yeah unfortunately I already noticed that `phpdbg` is not very stable. Unfortunately with my local configuration:
```
phpdbg 0.5.0
PHP 7.0.13-1+deb.sury.org~xenial+1, Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-1+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
```
I'm not seeing any segfault, so it's hard to investigate.

**Comment by tyranron** [comment]
@jails the problem is definitely in the first "magic" line. This worked earlier well and broke with latest PHP update. When I removing this line, everything works great.

You can try to play with newer PHP versions in official PHP Docker images.

I see 2 options here:
1. Just remove this line in upstream Kahlan repo. But what it can lead to?
2. I write a little hack in `Dockerfile` that will make `phpdbg` use a copy of `bin/kahlan` without first line.

**Comment by jails** [comment]
The php binary can be located in different locations according to different OS (/bin, /usr/bin, some ios paths, etc...). So the "magic line" is the standard way to get the correct location. It's [something kidda standard](https://github.com/sebastianbergmann/phpunit/blob/master/phpunit#L1).

However if the simple script:
```
#!/usr/bin/env php
<?php

echo "Hello World";
```
is segfaulting with phpdbg, maybe we can report the bug at https://bugs.php.net/ ?

**Comment by tyranron** [comment]
@jails sure, but those things take time 😟

Okay. Then I'll do an option 2 and report `phpdbg` bug additionally.

**Comment by jails** [comment]
Just had to run kahlan on windows with phpdbg and experienced the same issue.
Looks like the issue is related to phpdbg and is unpredictable so I wasn't able to create a minimal reproducible test case.
Btw by removing an unused `use` statement https://github.com/kahlan/kahlan/commit/eba0e20c093d714b393189df1bd6f694761d1210, the segfault disappear.
So if this "fix" also solve the segfault on your side I think we can close this issue and hoping somebody will nail it down in phpdbg when a more popular framework will be concerned.

**Comment by tyranron** [comment]
@jails thank you for taking care.

For 2.5 version I did an [in-place patch](https://github.com/kahlan/docker-image/blob/9637794003566f556e66c4ace6849b801691e5fc/Dockerfile.tmpl.php#L43-L49).
