### ISSUE TITLE
Re-link this repo on DockerHub for automated builds

### ISSUE THREAD

**Issue by tyranron** [kahlan/docker-image#3]
Hi, @jails.

Unfortunately, DockerHub has changed its platform and integration recently, so our automatic builds on pushes to this repo do not work anymore. Despite I have access to DockerHub repo settings, I have no access to `kahlan` org on GitHub, so cannot link/re-link repos for it.

Please, re-link this GitHub repository to DockerHub `kahlan/kahlan` repo on this page:  
https://cloud.docker.com/u/kahlan/repository/docker/kahlan/kahlan/builds/edit

So, I will be able to reconfigure automatic builds.

**Comment by jails** [comment]
It should be ok now, feel free to keep me posted !

**Comment by tyranron** [comment]
@jails it works, thanks a lot! 🙏
